name: Build WordPress PHP 7.4 (Manual)

on:
  workflow_dispatch:
    inputs:
      push_image:
        description: 'Push image to registry'
        required: true
        default: true
        type: boolean

jobs:
  build-php74:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build WordPress PHP 7.4 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=wordpress:php7.4-apache
          tags: |
            ghcr.io/quantcdn-templates/app-wordpress:php7.4
            ghcr.io/quantcdn-templates/app-wordpress:7.4
          push: ${{ inputs.push_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Build summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Base image**: wordpress:php7.4-apache" >> $GITHUB_STEP_SUMMARY
          echo "- **Tags**: ghcr.io/quantcdn-templates/app-wordpress:php7.4, ghcr.io/quantcdn-templates/app-wordpress:7.4" >> $GITHUB_STEP_SUMMARY
          echo "- **Platforms**: linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
          echo "- **Pushed**: ${{ inputs.push_image }}" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ inputs.push_image }}" == "true" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Usage" >> $GITHUB_STEP_SUMMARY
            echo '```yaml' >> $GITHUB_STEP_SUMMARY
            echo 'services:' >> $GITHUB_STEP_SUMMARY
            echo '  wordpress:' >> $GITHUB_STEP_SUMMARY
            echo '    image: ghcr.io/quantcdn-templates/app-wordpress:php7.4' >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi